version: '3.8'

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - kafka
    volumes:
      - ./proto:/proto

  pharma-service:
    build: ./pharma-service
    ports:
      - "50051:50051"
    depends_on:
      - order-service
    volumes:
      - ./proto:/proto

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - order-service

volumes:
  mongo_data:
